// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZbnRhTtqItyGjGWsMTBxPtHufTXD16E',
    appId: '1:441637616905:android:47255a5be531d169d3a7d8',
    messagingSenderId: '441637616905',
    projectId: 'gojdu-65243',
    storageBucket: 'gojdu-65243.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa50TI1URRy-Uj2EriI1-kaRWfME-Fn7g',
    appId: '1:441637616905:ios:bf549f85c8214bb0d3a7d8',
    messagingSenderId: '441637616905',
    projectId: 'gojdu-65243',
    storageBucket: 'gojdu-65243.appspot.com',
    iosClientId: '441637616905-4p1v0otfjv5cnkdqa7h9vc9jvtmtopge.apps.googleusercontent.com',
    iosBundleId: 'com.gojdu.app',
  );
}
